name: terraform
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: apply or destroy
        options:
          - apply
          - destroy
jobs:
  job:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform ${{ github.event.inputs.choice }}" -auto-approve
